language: python
python:
  - "2.7"
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
  - pip install numpy svmlight nose coverage PyYAML --use-mirrors
  - pip install scipy scikit-learn --use-mirrors
# command to run tests
script: python nltk/test/runtests.py
notifications:
  email: false
#  irc:
#    channels:
#      - "irc.freenode.org#nltk"
#    on_success: change
