language: python
python:
  - "2.7"
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends -qq python-scipy python-matplotlib python-numpy python-scikits-learn python-nose python-coverage python-yaml python-tk
  - dpkg -L python-matplotlib | grep pylab
install:
  - pip install svmlight #nose coverage PyYAML --use-mirrors
  - python -c "import nltk ; nltk.download(['book_grammars', 'cess_cat', 'cess_esp', 'comtrans', 'conll2007', 'floresta', 'framenet_v15', 'genesis', 'gutenberg', 'inaugural', 'indian', 'jeita', 'knbc', 'machado', 'maxent_treebank_pos_tagger', 'ptb', 'punkt', 'sample_grammars', 'sinica_treebank', 'stopwords', 'udhr'])"
# command to run tests
script: python nltk/test/runtests.py
notifications:
  email: false
#  irc:
#    channels:
#      - "irc.freenode.org#nltk"
#    on_success: change
